server:
  port: 5000

spring:
  main:
    allow-bean-definition-overriding: true

  servlet:
    encoding:
      charset: UTF-8
      force: true

  datasource:
    hikari:
      pool-name: SpringBootJPAHikariCP
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 300000
      connection-init-sql: set wait_timeout = 600
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${rds.username}
    password: ${rds.password}

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      default_batch_fetch_size: 100
    open-in-view: true

servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB

jwt:
  key: ${jwt_secret_key}